/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CackeGlobalLuncher: typeof import('./src/cake/global/luncher/CackeGlobalLuncher.vue')['default']
    CackeGlobalPageLuncher: typeof import('./src/cake/global/luncher/CackeGlobalPageLuncher.vue')['default']
    CakeGlobal: typeof import('./src/cake/global/CakeGlobal.vue')['default']
    CakeGlobalLoading: typeof import('./src/cake/global/ioading/CakeGlobalLoading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiGlobalLoading: typeof import('./src/ui/ui_global/ioading/UiGlobalLoading.vue')['default']
  }
}
